apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: clawguard-certs
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      selector:
        matchLabels:
          clawguard-cas: 'true'
      key: "ca.crt"
  target:
    configMap:
      key: "clawguard-certs.pem"
      metadata:
        labels:
          app.kubernetes.io/component: "trust-bundle"
