apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clawguard
configMapGenerator:
  - name: clawguard-config
    files:
      - assets/clawguard.yaml
  - name: json-server-config
    files:
      - assets/db.json
      - assets/routes.json
resources:
  - manifests/namespace.yaml
  - manifests/json-server.yaml
  - manifests/clawguard.yaml
  - manifests/certs/issuers.yaml
  - manifests/certs/cas.yaml
  - manifests/certs/certificates.yaml
  - manifests/certs/bundles.yaml